spring:
  datasource:
    url: jdbc:mysql://localhost:3306/today?serverTimezone=Asia/Seoul
    username: hyeryoung27
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500